services:
  mysql1:
    container_name: "mysql1"
    image: mysql:8.0
    env_file:
      - ./conf/mysql1/.env.local
    restart: "no"
    ports:
      - 3306:3306
    volumes:
      - ./conf/01-create-monitor-user.sql:/docker-entrypoint-initdb.d/01-create-monitor-user.sql
      - ./conf/mysql1/01-create-replication-user.sql:/docker-entrypoint-initdb.d/01-create-replication-user.sql
      - ./conf/mysql1/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - mysql1-data:/var/lib/mysql

  mysql2:
    container_name: "mysql2"
    image: mysql:8.0
    env_file:
      - ./conf/mysql2/.env.local
    restart: "no"
    ports:
      - 3307:3306
    depends_on:
      - mysql1
    volumes:
      - ./conf/01-create-monitor-user.sql:/docker-entrypoint-initdb.d/01-create-monitor-user.sql
      - ./conf/mysql2/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - mysql2-data:/var/lib/mysql

  mysql3:
    container_name: "mysql3"
    image: mysql:8.0
    env_file:
      - ./conf/mysql3/.env.local
    restart: "no"
    ports:
      - 3308:3306
    depends_on:
      - mysql1
    volumes:
      - ./conf/01-create-monitor-user.sql:/docker-entrypoint-initdb.d/01-create-monitor-user.sql
      - ./conf/mysql3/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - mysql3-data:/var/lib/mysql

  proxysql:
    container_name: proxysql
    image: proxysql/proxysql:latest
    ports:
      - "6033:6033"
      - "6032:6032"
      - "6080:6080"
    volumes:
      - ./conf/proxysql/proxysql.cnf:/etc/proxysql.cnf
      - proxysql-data:/var/lib/proxysql
    depends_on:
      - mysql1
      - mysql2
      - mysql3

volumes:
  mysql1-data:
  mysql2-data:
  mysql3-data:
  proxysql-data:
